name: Convert Markdown to Word and PDF

on:
  push:
    paths:
      - '*.md'  # Trigger only when .md files change
  workflow_dispatch: # Allows manual triggering

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run generate.sh to Build CV
      run: ./generate.sh

    - name: Commit and push generated files
      run: |
        git config --local user.name "Daniel Ryan"
        git config --local user.email "mail.dan.ryan@googlemail.com"
        git add cv.docx cv.pdf
        git commit -m "Update Word and PDF files [skip ci]" || echo "No changes to commit"
        git push